name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up the environment
        run: |
          pwd
          ls -l
          sudo chmod +x ./.github/setup-ci.sh
          sudo ./.github/setup-ci.sh
          pwd

      - name: Build the toolchain
        run: |
          pwd
          sudo chmod +x ./.github/setup-ci.sh
          sudo ./.github/build-toolchain.sh

      - name: Run the tests
        run: |
          pwd
          make MODE=ci

      - name: Clean
        run: |
          make clean
